#!/bin/bash
# Agent Journal Remote Installer
# 📓 "The human-readable diary of your AI agent's work."

set -e

VERSION="2.1.0"
REPO_URL="https://raw.githubusercontent.com/WoobWarb/agent-journal/main"
SKILL_FILE="Agent-Journal.md"
GLOBAL=false
FORCE=false

# Parse flags
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --global|-g) GLOBAL=true ;;
        --force|-f) FORCE=true ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
    shift
done

echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║   📓 Agent Journal Installer v$VERSION  ║"
echo "  ╚══════════════════════════════════════╝"
echo ""

# Set destination
if [ "$GLOBAL" = true ]; then
    DEST_DIR="$HOME/.agents"
    echo "  [i] Installing globally to: $DEST_DIR"
else
    DEST_DIR="$(pwd)/.agents"
    echo "  [i] Installing to project: $DEST_DIR"
fi

# Create directory
if [ ! -d "$DEST_DIR" ]; then
    mkdir -p "$DEST_DIR"
    echo "  [+] Created directory: .agents/"
else
    echo "  [=] Directory already exists: .agents/"
fi

DEST_PATH="$DEST_DIR/$SKILL_FILE"

# Check existing and extract session logs to preserve
EXISTING_SESSIONS=""
if [ -f "$DEST_PATH" ]; then
    echo ""
    echo "  [!] Agent-Journal.md already exists!"
    
    # Extract session logs starting with --- followed by ## [
    if command -v python3 &> /dev/null; then
        EXISTING_SESSIONS=$(python3 -c "import sys, re; content=open('$DEST_PATH','r',encoding='utf-8').read(); m=re.search(r'(?s)---\s*\r?\n\s*##\s*\[.*', content); print(m.group(0)) if m else None" 2>/dev/null)
    elif command -v python &> /dev/null; then
        EXISTING_SESSIONS=$(python -c "import sys, re; content=open('$DEST_PATH','r',encoding='utf-8').read(); m=re.search(r'(?s)---\s*\r?\n\s*##\s*\[.*', content); print(m.group(0)) if m else None" 2>/dev/null)
    fi
    
    if [ ! -z "$EXISTING_SESSIONS" ]; then
        echo "  [i] Found existing session logs. They will be preserved and merged."
    fi
    
    if [ "$FORCE" = false ]; then
        read -p "      Update installer files & merge existing journal? (Y/n) " answer
        if [[ "$answer" = "n" || "$answer" = "N" ]]; then
            echo "  [x] Installation cancelled."
            echo ""
            exit 0
        fi
    fi
fi

# Download
echo "  [*] Downloading template from GitHub..."
TEMP_PATH=$(mktemp)

if command -v curl &> /dev/null; then
    curl -fsSL "$REPO_URL/$SKILL_FILE" -o "$TEMP_PATH"
elif command -v wget &> /dev/null; then
    wget -q "$REPO_URL/$SKILL_FILE" -O "$TEMP_PATH"
else
    echo "  [!] Error: curl or wget is required."
    rm -f "$TEMP_PATH"
    exit 1
fi

if [ ! -z "$EXISTING_SESSIONS" ]; then
    cat "$TEMP_PATH" > "$DEST_PATH"
    echo -e "\n\n$EXISTING_SESSIONS" >> "$DEST_PATH"
    echo "  [+] Successfully updated Agent-Journal.md (merged old sessions)"
else
    cat "$TEMP_PATH" > "$DEST_PATH"
    echo "  [+] Successfully installed Agent-Journal.md"
fi
rm -f "$TEMP_PATH"

# Download AGENTS.md (universal rules for all AI agents)
echo "  [*] Downloading AGENTS.md (universal rules)..."
AGENTS_MD_PATH="$DEST_DIR/AGENTS.md"
if command -v curl &> /dev/null; then
    curl -fsSL "$REPO_URL/unified-skill.md" -o "$AGENTS_MD_PATH" && echo "  [+] Successfully installed AGENTS.md" || echo "  [!] Could not download AGENTS.md (non-fatal)."
elif command -v wget &> /dev/null; then
    wget -q "$REPO_URL/unified-skill.md" -O "$AGENTS_MD_PATH" && echo "  [+] Successfully installed AGENTS.md" || echo "  [!] Could not download AGENTS.md (non-fatal)."
fi

# Download viewer
echo "  [*] Downloading Journal Viewer..."
VIEWER_PATH="$DEST_DIR/journal-viewer.html"
if command -v curl &> /dev/null; then
    curl -fsSL "$REPO_URL/journal-viewer.html" -o "$VIEWER_PATH"
elif command -v wget &> /dev/null; then
    wget -q "$REPO_URL/journal-viewer.html" -O "$VIEWER_PATH"
fi
echo "  [+] Successfully installed journal-viewer.html"

# Create empty Agent-Journal.html placeholder
HTML_JOURNAL_PATH="$DEST_DIR/Agent-Journal.html"
if [ ! -f "$HTML_JOURNAL_PATH" ]; then
    cat > "$HTML_JOURNAL_PATH" << 'EOF'
<!-- Agent Journal HTML Companion -->
<!-- This file is auto-generated by your AI agent after each journal update. -->
<!-- Open it in a browser to view your journal as a beautiful dashboard. -->
EOF
    echo "  [+] Created Agent-Journal.html placeholder"
fi

# Download and run Agent Map (only for local installs)
if [ "$GLOBAL" = false ]; then
    echo "  [*] Downloading Agent Map generator..."
    MAP_SCRIPT_PATH="$(pwd)/agent-map.py"
    if command -v curl &> /dev/null; then
        curl -fsSL "$REPO_URL/agent-map.py" -o "$MAP_SCRIPT_PATH"
    else
        wget -q "$REPO_URL/agent-map.py" -O "$MAP_SCRIPT_PATH"
    fi
    echo "  [+] Successfully downloaded agent-map.py"
    echo "  [*] Generating Project Map..."
    if command -v python3 &> /dev/null; then
        python3 "$MAP_SCRIPT_PATH"
    elif command -v python &> /dev/null; then
        python "$MAP_SCRIPT_PATH"
    else
        echo "  [!] Could not run Python automatically."
    fi
fi

# Add to .gitignore
if [ -f ".gitignore" ]; then
    if ! grep -q ".agents/" .gitignore; then
        echo -e "\n# Agent Journal\n.agents/" >> .gitignore
        echo "  [+] Added .agents/ to .gitignore"
    fi
fi

# Configure AI Auto-Journaling (all platforms)
if [ "$GLOBAL" = false ]; then
    echo "  [*] Configuring AI Auto-Journaling for all platforms..."
    RULE_TEXT="\n# Agent Journal Rules\n- Read and follow .agents/AGENTS.md for journaling and context rules.\n- PRE-JOURNALING: ALWAYS write an initial entry in .agents/Agent-Journal.md BEFORE making any code changes. Set status to In Progress and list planned actions.\n- COMPLETION: Once work is complete, update the entry's status to Complete.\n- Read .agents/PROJECT_MAP.md (if it exists) before starting.\n- Do not ask for permission to journal, just do it automatically.\n"

    # Cursor
    if ! ([ -f ".cursorrules" ] && grep -q "Agent Journal" ".cursorrules"); then
        printf "%b" "$RULE_TEXT" >> ".cursorrules"
        echo "  [+] Configured .cursorrules"
    fi

    # Windsurf
    if ! ([ -f ".windsurfrules" ] && grep -q "Agent Journal" ".windsurfrules"); then
        printf "%b" "$RULE_TEXT" >> ".windsurfrules"
        echo "  [+] Configured .windsurfrules"
    fi

    # Claude Code - CLAUDE.md (uses @import so rules are always loaded)
    if [ ! -f "CLAUDE.md" ]; then
        printf "# Project Rules\n\n@.agents/AGENTS.md\n" > "CLAUDE.md"
        echo "  [+] Created CLAUDE.md"
    elif ! grep -q "AGENTS\.md" "CLAUDE.md"; then
        printf "\n@.agents/AGENTS.md\n" >> "CLAUDE.md"
        echo "  [+] Updated CLAUDE.md with journal import"
    fi

    # GitHub Copilot - .github/copilot-instructions.md
    mkdir -p ".github"
    if ! ([ -f ".github/copilot-instructions.md" ] && grep -q "Agent Journal" ".github/copilot-instructions.md"); then
        printf "%b" "$RULE_TEXT" >> ".github/copilot-instructions.md"
        echo "  [+] Configured .github/copilot-instructions.md"
    fi

    # Antigravity
    mkdir -p ".antigravity"
    if [ ! -f ".antigravity/extensions.json" ]; then
        cat > ".antigravity/extensions.json" << 'EOF'
{"version":"1.0","extensions":[{"id":"unified-agent-skill","name":"Agent Context + Journal","description":"Universal journaling, context saving, and project mapping","enabled":true,"path":"../.agents/AGENTS.md"}]}
EOF
        echo "  [+] Configured .antigravity/extensions.json"
    fi
fi

echo ""
echo "  ✅ Ready to start journaling!"
echo ""
echo "  ✨ Auto-Journaling configured for:"
echo "    - Claude Code    (CLAUDE.md)"
echo "    - Cursor         (.cursorrules)"
echo "    - Windsurf       (.windsurfrules)"
echo "    - GitHub Copilot (.github/copilot-instructions.md)"
echo "    - Antigravity    (.antigravity/extensions.json)"
echo "  🌐 HTML Companion enabled. Agent will generate Agent-Journal.html after each session."
echo ""
echo "  📊 Open .agents/Agent-Journal.html in any browser to view your journal dashboard"
echo ""
echo "  ──────────────────────────────────────"
echo "  Options:  install.sh --global  (install to ~/.agents/)"
echo "            install.sh --force   (overwrite without asking)"
echo ""
