# Agent Journal Remote Installer
# 📓 "The human-readable diary of your AI agent's work."

param(
    [switch]$Global,
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$Version = "2.1.0"

Write-Host ""
Write-Host "  ╔══════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║   📓 Agent Journal Installer v$Version  ║" -ForegroundColor Cyan
Write-Host "  ╚══════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# 1. Configuration
$RepoUrl = "https://raw.githubusercontent.com/WoobWarb/agent-journal/main"
$SkillFile = "Agent-Journal.md"

if ($Global) {
    $DestDir = Join-Path $env:USERPROFILE ".agents"
    Write-Host "  [i] Installing globally to: $DestDir" -ForegroundColor Gray
} else {
    $DestDir = Join-Path (Get-Location) ".agents"
    Write-Host "  [i] Installing to project: $DestDir" -ForegroundColor Gray
}

# 2. Ensure .agents directory exists
if (-not (Test-Path $DestDir)) {
    New-Item -ItemType Directory -Path $DestDir | Out-Null
    Write-Host "  [+] Created directory: .agents/" -ForegroundColor Green
} else {
    Write-Host "  [=] Directory already exists: .agents/" -ForegroundColor DarkGray
}

# 3. Check for existing file and preserve sessions
$DestPath = Join-Path $DestDir $SkillFile
$ExistingSessions = ""

if (Test-Path $DestPath) {
    Write-Host ""
    Write-Host "  [!] Agent-Journal.md already exists!" -ForegroundColor Yellow
    
    $content = Get-Content $DestPath -Raw
    if ($content -match "(?s)(---\s*\r?\n\s*##\s*\[.*)") {
        $ExistingSessions = $Matches[1]
        Write-Host "  [i] Found existing session logs. They will be preserved and merged." -ForegroundColor Gray
    }
    
    if (-not $Force) {
        $answer = Read-Host "      Update installer files & merge existing journal? (Y/n)"
        if ($answer -eq "n" -or $answer -eq "N") {
            Write-Host "  [x] Installation cancelled." -ForegroundColor Red
            Write-Host ""
            return
        }
    }
}

# 4. Download the skill template
Write-Host "  [*] Downloading template from GitHub..." -ForegroundColor Gray

try {
    $TempPath = [System.IO.Path]::GetTempFileName()
    Invoke-WebRequest -Uri "$RepoUrl/$SkillFile" -OutFile $TempPath -UseBasicParsing
    $NewTemplate = Get-Content $TempPath -Raw
    Remove-Item $TempPath
    
    if ($ExistingSessions) {
        $MergedContent = $NewTemplate.TrimEnd() + "`n`n" + $ExistingSessions.Trim() + "`n"
        Set-Content -Path $DestPath -Value $MergedContent -Encoding UTF8
        Write-Host "  [+] Successfully updated Agent-Journal.md (merged old sessions)" -ForegroundColor Green
    } else {
        Set-Content -Path $DestPath -Value $NewTemplate -Encoding UTF8
        Write-Host "  [+] Successfully installed Agent-Journal.md" -ForegroundColor Green
    }
} catch {
    Write-Host "  [!] Download or write failed: $_" -ForegroundColor Red
    return
}

# 4b. Download AGENTS.md (universal rules for all AI agents)
$AgentsMdPath = Join-Path $DestDir "AGENTS.md"
Write-Host "  [*] Downloading AGENTS.md (universal rules)..." -ForegroundColor Gray
try {
    Invoke-WebRequest -Uri "$RepoUrl/unified-skill.md" -OutFile $AgentsMdPath -UseBasicParsing
    Write-Host "  [+] Successfully installed AGENTS.md" -ForegroundColor Green
} catch {
    Write-Host "  [!] Could not download AGENTS.md (non-fatal)." -ForegroundColor Yellow
}

# 4c. Download journal-viewer.html (HTML companion viewer)
$ViewerDestPath = Join-Path $DestDir "journal-viewer.html"
Write-Host "  [*] Downloading HTML viewer..." -ForegroundColor Gray
try {
    Invoke-WebRequest -Uri "$RepoUrl/journal-viewer.html" -OutFile $ViewerDestPath -UseBasicParsing
    Write-Host "  [+] Successfully installed journal-viewer.html" -ForegroundColor Green
} catch {
    Write-Host "  [!] Could not download journal-viewer.html (non-fatal)." -ForegroundColor Yellow
}

# 4d. Create empty Agent-Journal.html placeholder (will be populated by agent)
$HtmlJournalPath = Join-Path $DestDir "Agent-Journal.html"
if (-not (Test-Path $HtmlJournalPath)) {
    $EmptyHtml = "<!-- Agent Journal HTML Companion -->`n<!-- This file is auto-generated by your AI agent after each journal update. -->`n<!-- Open it in a browser to view your journal as a beautiful dashboard. -->"
    Set-Content -Path $HtmlJournalPath -Value $EmptyHtml -Encoding UTF8
    Write-Host "  [+] Created Agent-Journal.html placeholder" -ForegroundColor Green
}

# 5. Download and run Agent Map (only for local installs)
if (-not $Global) {
    Write-Host "  [*] Downloading Agent Map generator..." -ForegroundColor Gray
    $MapScriptPath = Join-Path (Get-Location) "agent-map.py"
    try {
        Invoke-WebRequest -Uri "$RepoUrl/agent-map.py" -OutFile $MapScriptPath -UseBasicParsing
        Write-Host "  [+] Successfully downloaded agent-map.py" -ForegroundColor Green
        Write-Host "  [*] Generating Project Map..." -ForegroundColor Gray
        python $MapScriptPath
    } catch {
        Write-Host "  [!] Failed to download or run agent-map.py." -ForegroundColor Yellow
    }
}

# 6. Add to .gitignore if not already there
$gitignorePath = Join-Path (Get-Location) ".gitignore"
if (Test-Path $gitignorePath) {
    $content = Get-Content $gitignorePath -Raw
    if ($content -notmatch "\.agents/") {
        Add-Content $gitignorePath "`n# Agent Journal`n.agents/"
        Write-Host "  [+] Added .agents/ to .gitignore" -ForegroundColor Green
    }
}

# 7. Configure AI Auto-Journaling (all platforms)
if (-not $Global) {
    Write-Host "  [*] Configuring AI Auto-Journaling for all platforms..." -ForegroundColor Gray
    $RuleText = "`n# Agent Journal Rules`n- Read and follow .agents/AGENTS.md for journaling and context rules.`n- PRE-JOURNALING: ALWAYS write an initial entry in .agents/Agent-Journal.md BEFORE making any code changes. Set status to In Progress and list planned actions.`n- COMPLETION: Once work is complete, update the entry's status to Complete.`n- Read .agents/PROJECT_MAP.md (if it exists) before starting.`n- Do not ask for permission to journal, just do it automatically.`n"

    # Cursor
    $cursorPath = Join-Path (Get-Location) ".cursorrules"
    if (-not (Test-Path $cursorPath) -or -not ((Get-Content $cursorPath -Raw -ErrorAction SilentlyContinue) -match "Agent Journal")) {
        Add-Content $cursorPath $RuleText
        Write-Host "  [+] Configured .cursorrules" -ForegroundColor Green
    }

    # Windsurf
    $windsurfPath = Join-Path (Get-Location) ".windsurfrules"
    if (-not (Test-Path $windsurfPath) -or -not ((Get-Content $windsurfPath -Raw -ErrorAction SilentlyContinue) -match "Agent Journal")) {
        Add-Content $windsurfPath $RuleText
        Write-Host "  [+] Configured .windsurfrules" -ForegroundColor Green
    }

    # Claude Code - CLAUDE.md
    $claudeMd = Join-Path (Get-Location) "CLAUDE.md"
    if (-not (Test-Path $claudeMd)) {
        Set-Content $claudeMd "# Project Rules`n`nRead and follow `.agents/AGENTS.md` for journaling and context rules.`n$RuleText" -Encoding UTF8
        Write-Host "  [+] Created CLAUDE.md" -ForegroundColor Green
    } elseif (-not ((Get-Content $claudeMd -Raw) -match "Agent Journal")) {
        Add-Content $claudeMd "`n$RuleText"
        Write-Host "  [+] Updated CLAUDE.md with journal rules" -ForegroundColor Green
    }

    # GitHub Copilot - .github/copilot-instructions.md
    $githubDir = Join-Path (Get-Location) ".github"
    if (-not (Test-Path $githubDir)) {
        New-Item -ItemType Directory -Path $githubDir -Force | Out-Null
    }
    $copilotPath = Join-Path $githubDir "copilot-instructions.md"
    if (-not (Test-Path $copilotPath) -or -not ((Get-Content $copilotPath -Raw -ErrorAction SilentlyContinue) -match "Agent Journal")) {
        Add-Content $copilotPath $RuleText
        Write-Host "  [+] Configured .github/copilot-instructions.md" -ForegroundColor Green
    }

    # Antigravity
    $antigravDir = Join-Path (Get-Location) ".antigravity"
    if (-not (Test-Path $antigravDir)) {
        New-Item -ItemType Directory -Path $antigravDir -Force | Out-Null
    }
    $extJsonPath = Join-Path $antigravDir "extensions.json"
    if (-not (Test-Path $extJsonPath)) {
        $extJson = '{"version":"1.0","extensions":[{"id":"unified-agent-skill","name":"Agent Context + Journal","description":"Universal journaling, context saving, and project mapping","enabled":true,"path":"../.agents/AGENTS.md"}]}'
        Set-Content $extJsonPath $extJson -Encoding UTF8
        Write-Host "  [+] Configured .antigravity/extensions.json" -ForegroundColor Green
    }
}

# 8. Success Message
Write-Host ""
Write-Host "  ✅ Ready to start journaling!" -ForegroundColor Cyan
Write-Host ""
Write-Host "  ✨ Auto-Journaling configured for:" -ForegroundColor Green
Write-Host "    - Claude Code   (CLAUDE.md)" -ForegroundColor Gray
Write-Host "    - Cursor        (.cursorrules)" -ForegroundColor Gray
Write-Host "    - Windsurf      (.windsurfrules)" -ForegroundColor Gray
Write-Host "    - GitHub Copilot (.github/copilot-instructions.md)" -ForegroundColor Gray
Write-Host "    - Antigravity   (.antigravity/extensions.json)" -ForegroundColor Gray
Write-Host "  🌐 HTML Companion enabled. Agent will generate Agent-Journal.html after each session." -ForegroundColor Green
Write-Host ""
Write-Host "  ──────────────────────────────────────" -ForegroundColor DarkGray
Write-Host "  Options:  install.ps1 -Global  (install to ~\.agents\)" -ForegroundColor DarkGray
Write-Host "            install.ps1 -Force   (overwrite without asking)" -ForegroundColor DarkGray
Write-Host ""
